### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by julianeweller** [Schwank-Lab/epridict#1]
Hey, 
I've tried to install the model and ran into the following issues: 

1. minor: You could add this to the installation description:
`chmod +x epridict_download_encode.sh `

2. Downloading the encode files led to an error for me:
```
(epridict)$ ./epridict_download_encode.sh light
This will download 6 ENCODE datasets with a total of 5.3 GB to the folder 'bigwig'. Are you sure to continue (yes/no)? yes
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
KeyError: 'light_model'
```

This was solved by replacing TARGET_COLUMN="light_model" with TARGET_COLUMN="slim_model" due to the column naming in the related csv.

But then it worked :)

**Comment by mathinic** [comment]
Hi Juliane,
Thanks for raising the issue!
I just extended the installation manual and fixed the column name in the .csv file ("light" model had different names in the course of developing ePRIDICT :) ).

Best,
Nicolas
